services:
    mongo:
        image: 'mongo:${MONGO_VERSION:-6}'
        command: --auth --noscripting
        restart: unless-stopped
        environment:
            MONGO_INITDB_DATABASE: '${DB_DATABASE:-binance-api}'
            MONGO_INITDB_ROOT_USERNAME: '${DB_USERNAME:-binance}'
            MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'binance-mongo:/data/db'
            - 'binance-mongo-config:/data/configdb'
        networks:
            - binance
        ports:
          - '27017:27017'
        healthcheck:
            test: [ "CMD-SHELL", "echo 'db.stats().ok' | mongosh localhost:27017/test --quiet"]
            start_period: 40s

    binance-api:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                APP_ENV: '${APP_ENV:-local}'
                NODE_VERSION: '${NODE_VERSION:-16}'
        image: binance/binance-api
        pull_policy: never
        restart: unless-stopped
        environment:
            HOST_UID: '${HOST_UID:-1000}'
            HOST_GID: '${HOST_GID:-1000}'
            BINANCE_MONGODB_URL: '${MONGODB_URL:-mongodb://$DB_USERNAME:$DB_PASSWORD@mongo:27017}'
            BINANCE_MONGODB_NAME: 'binance-api'
            BINANCE_WS: '${BINANCE_WS}'
            BINANCE_STORAGE_PATH: '${BINANCE_STORAGE_PATH:-/home/node/app/storage}'
            BINANCE_KEYPATH: '${BINANCE_KEYPATH}'
            BINANCE_CRTPATH: '${BINANCE_CRTPATH}'
            BINANCE_LOGFILE: '${BINANCE_LOGFILE}'
            BINANCE_BIND: '${BINANCE_BIND:-localhost}'
            BINANCE_PORT: '${BINANCE_PORT:-7000}'
        volumes:
            -   type: bind
                source: '.'
                target: '/home/node/app'
            -   type: bind
                source: '${HOME}/.npm'
                target: '/tmp/.npm'
        networks:
            - binance
        ports:
          - '7000:7000'
        healthcheck:
            test: [ "CMD-SHELL", "curl --fail http://localhost:7000/ping || exit 1" ]
            start_period: 2m

networks:
    binance:
        driver: bridge

volumes:
    binance-mongo:
        driver: local
    binance-mongo-config:
        driver: local
